// This code was generated by an Alaska Airlines operated instance of Azure OpenAI using the GPT 4o model.

// Example interfaces for UserPreferences, Seat, and FeedbackData
export interface UserPreferences {
  windowSeat: boolean;
  aisleSeat: boolean;
  extraLegroom: boolean;
}

export interface Seat {
  id: number;
  isWindow: boolean;
  isAisle: boolean;
  hasExtraLegroom: boolean;
}

export interface FeedbackData {
  seatId: number;
  userId: number;
  rating: number;
  comments: string;
}